---
title: "Drosophila Burst Speed"
author: "Jeff Walker"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, echo=FALSE}
# wrangling packages
library(data.table) # magical data frames
library(here) # here makes a project transportable
library(janitor) # clean_names
library(readxl) # read_excel, duh!
library(writexl) # write_xlsx, duh!
library(stringr) # text wrangling

# analysis packages
library(lme4)
library(lmerTest)
library(emmeans) # the workhorse for inference


# graphing packages
library(ggsci) # color palettes
library(ggpubr) # publication quality plots
library(ggforce) # better jitter
library(cowplot) # combine plots
library(knitr) # kable tables
library(kableExtra) # kable_styling tables

# ggplot_the_model.R packages not loaded above
library(insight)
library(lazyWeave)
library(afex) # aov4

# use here from the here package
here <- here::here
# use clean_names from the janitor package
clean_names <- janitor::clean_names
# use transpose from data.table
transpose <- data.table::transpose

# load functions used by this text written by me
# ggplot_the_model.R needs to be in the folder "R"
# if you didn't download this and add to your R folder in your
# project, then this line will cause an error

source(here("code", "ggplot_the_model.R"))
source(here("code", "ggptm.R"))

data_folder <- "data"

# constants
dial_to_speed <- 6.42237212 # from my smoke test with screens and forcing through origin

```


# Burst analysis
## Simons-Walker data
### Import
The major analyis is an estimate of the effects.

```{r import}
subfolder <- "burst speed/simons-walker "
filename <- "Wind Tunnel minus days>6.xlsx"
in_path <- here(data_folder, subfolder, filename)

simons <- read_xlsx(in_path,
                    range = "A1:H108") |>
  clean_names() |>
  data.table()

simons[, id := .I]
simons[, treatment := factor(treatment, levels = c("CN", "AA"))]
simons[, sex := factor(sex, levels = c("M", "F"))]
simons[, line := paste0(treatment, line) |>
       factor(levels = c("CN1", "CN2", "AA1", "AA2"))]
simons[, wind_speed := dial_50 * dial_to_speed]
```


```{r simons-init-plot}
ggplot(data = simons,
       aes(x = line,
           y = wind_speed)) +
  geom_jitter(width = 0.1)
```


```{r simons-sample-means}

simons_summary <- simons[, .(wind_speed = mean(wind_speed)), by = .(treatment, sex, line)]
simons_summary
```

```{r simons-room-temp}
lm_ancova <- lm(wind_speed ~ treatment * sex + room_temp, data = simons)
coef(summary(lm_ancova))


ggplot(data = simons,
       aes(x = room_temp,
           y = wind_speed,
           color = treatment)) +
  geom_point() +
#  geom_ancova(lm_ancova) +
  NULL
```

```{r simons-balance}
simons[, .(N = .N), by = .(line, sex)]
```
### Estimate Treatment Effects

```{r simons-lmm-random-intercept}
lmm_all <- lmer(wind_speed ~ treatment * sex + (1 | line), data = simons)
coef(summary(lmm_all))
sigma <- summary(lmm_all)$sigma

lmm_all_emm <- emmeans(lmm_all, specs = c("treatment", "sex"))

cn_m <- c(1,0,0,0)
aa_m <- c(0,1,0,0)
cn_f <- c(0,0,1,0)
aa_f <- c(0,0,0,1)
aa_contrast <- list(
  list(male = aa_m - cn_m),
  list(female = aa_f - cn_f)
)

lmm_all_pairs <- contrast(lmm_all_emm,
                      method = aa_contrast) |>
  summary(infer = TRUE) |>
  data.table()
lmm_all_pairs[, effect_std := estimate / sigma]

lmm_all_emm
lmm_all_pairs
```

### Plot

1. Separate sex
2. plot each line as a separate X value, show the data
3. get line means from lmm

```{r simons-conditional-means}
# compute conditional means
newdat <- expand.grid(
  line = levels(simons$line),
  sex = levels(simons$sex)
) |>
  data.table()
newdat[, treatment := ifelse(substr(newdat$line, 1, 2) == "AA", "AA", "CN")]
newdat[, fit := predict(lmm_all, newdata = newdat)]

# check with my own math
coefs <- coef(lmm_all)$line
mm_males <- matrix(c(1,0,0,0,
                       1,0,0,0,
                       1,1,0,0,
                       1,1,0,0), nrow=4)
mm_females <- matrix(c(1,0,1,0,
                       1,0,1,0,
                       1,1,1,1,
                       1,1,1,1), nrow=4)
male_means <- as.matrix(coefs) %*% mm_males |> diag()
female_means <- as.matrix(coefs) %*% mm_females |> diag()

# compare with raw means
fixed_means <- simons[, .(speed = mean(wind_speed)),
                      by = .(sex, line, treatment)]
fixed_means

```

```{r simons-conditional-mean-plot}

means_plot <- function(plot_sex = "F", title = "Female"){
  offset <- 0.15
  x_breaks <- c(1-offset, 1+offset, 2-offset, 2+offset)
  
  plot_data <- simons[, .SD, .SDcols = c("treatment", "line", "sex", "wind_speed")]
  treatment_means <- lmm_all_emm |> 
    summary() |>
    data.table()
  treatment_means[treatment == "CN", x := 1]
  treatment_means[treatment == "AA", x := 2]
  plot_data[line == "CN2", x := 1 + offset]
  plot_data[line == "CN1", x := 1 - offset]
  plot_data[line == "CN2", x := 1 + offset]
  plot_data[line == "AA1", x := 2 - offset]
  plot_data[line == "AA2", x := 2 + offset]
  newdat[line == "CN1", x := 1 - offset]
  newdat[line == "CN2", x := 1 + offset]
  newdat[line == "AA1", x := 2 - offset]
  newdat[line == "AA2", x := 2 + offset]
  
  gg <- ggplot(data = plot_data[sex == plot_sex],
               aes(x = x,
                   y = wind_speed,
                   color = treatment)) +
    
    # raw data
    # geom_sina(maxwidth = 0.5,
    #           color = "gray") +
    geom_jitter(width = 0.05,
                height = 0,
                color = "gray") +
    
    # line means
    geom_point(data = newdat[sex == plot_sex],
               aes(x = x,
                   y = fit),
               size = 2) +
    
    # treatment means and CI
    geom_point(data = treatment_means[sex == plot_sex],
               aes(x = x,
                   y = emmean),
               size = 3) +
    geom_errorbar(data = treatment_means[sex == plot_sex],
                  aes(x = x,
                      y = emmean,
                      ymin = lower.CL,
                      ymax = upper.CL),
                  width = 0) +
    
    # clean plot
    ylab("Max Burst Speed (cm/s)") +
    scale_color_manual(values = pal_okabe_ito) +
    scale_x_continuous(breaks = x_breaks,
                       labels = c("CN1", "CN2", "AA1", "AA2")) +
    theme_pubr() +
    theme(legend.position="none",
          axis.title.x = element_blank()) +
    coord_cartesian(xlim = c(0.7, 2.3)) +
    ggtitle(title)
  return(gg)
}

gg_f <- means_plot(plot_sex = "F", title = "Female")
gg_m <- means_plot(plot_sex = "M", title = "Male")
plot_grid(gg_f, gg_m, ncol = 2)
```

### Other models
With room_temp covariate (supplement)

```{r simons-lmm-random-intercept}
lmm_all <- lmer(wind_speed ~ treatment * sex + room_temp + (1 | line), data = simons)
coef(summary(lmm_all))
sigma <- summary(lmm_all)$sigma

lmm_all_emm <- emmeans(lmm_all, specs = c("treatment", "sex"))

cn_m <- c(1,0,0,0)
aa_m <- c(0,1,0,0)
cn_f <- c(0,0,1,0)
aa_f <- c(0,0,0,1)
aa_contrast <- list(
  list(male = aa_m - cn_m),
  list(female = aa_f - cn_f)
)

lmm_all_pairs <- contrast(lmm_all_emm,
                      method = aa_contrast) |>
  summary(infer = TRUE) |>
  data.table()
lmm_all_pairs[, effect_std := estimate / sigma]

lmm_all_emm
lmm_all_pairs

```
```{r simons-classical-nested-anova}
str(simons)
m1 <- aov(wind_speed ~ treatment * sex + Error(line / sex),
          data = simons)
summary(m1)

m1_male <- aov(wind_speed ~ treatment + Error(line),
          data = simons)
```



```{r}
lmm_m <- lmer(wind_speed ~ treatment + (1 | line), data = simons[sex == "M"])
lmm_f <- lmer(wind_speed ~ treatment + (1 | line), data = simons[sex == "F"])
lmm_m_emm <- emmeans(lmm_m, specs = "treatment")
lmm_f_emm <- emmeans(lmm_f, specs = "treatment")
lmm_m_pairs <- contrast(lmm_m_emm,
                        method = "revpairwise") |>
  summary(infer = TRUE)
lmm_f_pairs <- contrast(lmm_f_emm,
                        method = "revpairwise") |>
  summary(infer = TRUE)
ggptm(lmm_m, lmm_m_emm, lmm_m_pairs, show_nest_data = TRUE, nest_id = "line")
ggptm(lmm_f, lmm_f_emm, lmm_f_pairs, show_nest_data = TRUE, nest_id = "line")
```


Some plots

```{r}
ggptm(lmm_all, lmm_all_emm, lmm_all_pairs, show_nest_data = TRUE, nest_id = "line")
```


```{r}
set.seed(1) # for jitter


group_list <- c( "CN1 M", "CN2 M", "CN1 F", "CN2 F", "AA1 M", "AA2 M", "AA1 F", "AA2 F")
simons[, group := paste(line, sex) |>
        factor(levels = group_list)]
simons[, x := as.integer(group) + rnorm(n = nrow(simons), sd = 0.1)]

label_list <- str_replace_all(group_list, " ", "\n")
ggplot(data = simons,
       aes(x = x,
           y = wind_speed)) +
  geom_point() +
  scale_x_continuous(breaks = 1:8, labels = label_list) +
  ylab("Max Burst Speed (cm/s)") +
  theme_pubr()
```

## Jess Wheeler data
```{r jess-clean-his-files}
subfolder <- "burst speed/jess wheeler/sent from jess/raw"
filename <- "02.14.10.xlsx"
in_path <- here(data_folder, subfolder, filename)

  file_i <- read_xlsx(in_path,
                    range = "a1:c1000") |>
    clean_names() |>
    data.table() |>
    na.omit()
  # angle is flight angle in degrees from 1,0
  # length is flight distance over 1 frame
  colnames(file_i)[1] <- "id"
  file_i[, treatment := substr(id,1,2)]
  file_i[, line := substr(id,1,3)]
  file_i[, sex := substr(id, 4,4)]
  file_i[, dial := substr(id, 5,6) |> as.integer()]
  file_i[, date := substr(id, 8,15)]
 
  check_n <- file_i[, .(N = .N),
     by = .(date, sex, treatment, line, id)]
  check_n[N >=6, id]

  check_id <- check_n[, .(N = .N), 
     by = .(date, sex, treatment, line)]
setorder(check_id, sex, treatment, line, date)

```

```{r jess-import-cleaned}

subfolder <- "burst speed/jess wheeler/sent from jess/raw"
subfolder_path <- here(data_folder, subfolder)

files <- list.files(
  path = subfolder_path,
  pattern = "\\.xlsx$",
  full.names = TRUE
)

jess <- data.table(NULL)

for(i in 1:length(files)){
  in_path <- files[i]
  
  file_i <- read_xlsx(in_path,
                    range = "a1:c1000") |>
    clean_names() |>
    data.table() |>
    na.omit()
  # angle is flight angle in degrees from 1,0
  # length is flight distance over 1 frame
  colnames(file_i)[1] <- "id"
  file_i[, treatment := substr(id,1,2)]
  file_i[, line := substr(id,1,3)]
  file_i[, sex := substr(id, 4,4)]
  file_i[, dial := substr(id, 5,6) |> as.integer()]
  file_i[, date := substr(id, 8,15)]
  
  # performance measures
  file_i[, theta := ifelse(angle < 0,
                         -(angle + 180),
                         180-angle)]
  file_i[, wind_jess := 7.3888 * dial]
  file_i[, wind_jaw := 6.42237212 * dial]
  file_i[, disp.x := length * cos(theta * pi/180)]
  file_i[, disp.y := length * sin(theta * pi/180)]
  file_i[, wind.x := wind_jess / 30]
  file_i[, vel := sqrt((wind.x + disp.x)^2 + disp.y^2) * 30]
  
  jess <- rbind(jess, file_i)
  
}

```

```{r jess-summary}

# first compute max within each id
jess_max_id <- jess[, .(wind_max = mean(wind_jess),
                        vel_max = mean(vel),
                        N = .N),
     by = .(date, treatment, line, sex, id)]

jess_sum <- jess_max_id[, .(wind_max = mean(wind_max),
                            vel_max = mean(vel_max),
                    N = .N), 
     by = .(date, sex, treatment, line)]
setorder(jess_sum, sex, treatment, line, date)
```

```{r jess-analysis}
lmm1 <- lmer(wind_max ~ treatment + (1 | line), data = jess_sum[sex == "f"])
lmm1_means <- emmeans(lmm1, specs = "treatment")
lmm1_pairs <- contrast(lmm1_means,
                       method = "trt.vs.ctrl",
                       adjust = "none") |>
  summary(infer = TRUE)
ggptm(lmm1, lmm1_means, lmm1_pairs,
      nest_id = "line",
      show_nest_data = TRUE)

lmm1 <- lmer(wind_max ~ treatment + (1 | line), data = jess_sum[sex == "m"])
lmm1_means <- emmeans(lmm1, specs = "treatment")
lmm1_pairs <- contrast(lmm1_means,
                       method = "trt.vs.ctrl",
                       adjust = "none") |>
  summary(infer = TRUE)
ggptm(lmm1, lmm1_means, lmm1_pairs,
      nest_id = "line",
      show_nest_data = TRUE)

```

## Combined

```{r burst-combined-plot}
burst1 <- data.table(
  experiment = "Ind",
  simons[, .SD, .SDcols = c("treatment", "line", "sex", "wind_speed")])
burst2 <- data.table(
  experiment = "Gr",
  jess[, .SD, .SDcols = c("treatment", "line", "sex", "wind_jess")])
setnames(burst2, old = "wind_jess", new = "wind_speed")
burst <- rbind(burst1, burst2)
burst[, exp_line := paste(line, experiment)]

ggplot(data = burst,
       aes(x = exp_line,
           y = wind_speed)) +
  geom_jitter(width = 0.1)



```

# Kinematic analysis


```{r free-flight-import}
subfolder <- "kinematics/free flight/processed"
filename <- "frequency data.xlsx"
in_path <- here(data_folder, subfolder, filename)

free_flight <- read_xlsx(in_path,
                   sheet = "frequency data") |>
  clean_names() |>
  data.table() |>
  na.omit() # safe there is one row with no data
free_flight[, treatment := ifelse(treatment == "aa", "AA", "CN")]
free_flight[, treatment := factor(treatment, levels = c("CN", "AA"))]
free_flight[, sex := ifelse(sex == "m", "M", "F")]
free_flight[, sex := factor(sex, levels = c("M", "F"))]

tunnel <- free_flight[experiment == "tunnel"]
```

```{r}
freq_f <- lm(f ~ treatment * v1, data = tunnel[sex == "F"])
coef(summary(freq_f))

gg_freq_f <- ggplot(data = tunnel[sex == "F"],
                    aes(x = v1,
                        y = f,
                        color = treatment)) +
  geom_point() +
  geom_ancova(freq_f) +
  theme_pubr()

freq_m <- lm(f ~ treatment * v1, data = tunnel[sex == "M"])
coef(summary(freq_m))

gg_freq_m <- ggplot(data = tunnel[sex == "M"],
                    aes(x = v1,
                        y = f,
                        color = treatment)) +
  geom_point() +
  geom_ancova(freq_m) +
  theme_pubr()

plot_grid(gg_freq_m, gg_freq_f, ncol = 2)
```


```{r free-flight-import}
subfolder <- "kinematics/free flight/processed"
filename <- "init_data.xlsx"
in_path <- here(data_folder, subfolder, filename)

free_flight_init <- read_xlsx(in_path,
                   sheet = "init_data") |>
  clean_names() |>
  data.table()
setnames(free_flight_init, old = "treat", new = "treatment")
free_flight_init[, treatment := ifelse(treatment == "aa", "AA", "CN")]
free_flight_init[, treatment := factor(treatment, levels = c("CN", "AA"))]
free_flight_init[, sex := ifelse(sex == "m", "M", "F")]
free_flight_init[, sex := factor(sex, levels = c("M", "F"))]

free_flight_init[, v_bar := (v1+v2)/2]
```

```{r}
lm1 <- lm(f ~ treatment + v_bar, data = free_flight_init[sex == "F"])
coef(summary(lm1))

ggplot(data = free_flight_init[sex == "F"],
       aes(x = v_bar,
           y = f,
           color = treatment)) +
  geom_point() +
#  geom_ancova(lm1) +
  theme_pubr()
```

```{r}

```


# Wingshape analysis
